### ISSUE TITLE
Segment not saving values

### ISSUE THREAD

**Issue by rakshithsj30** [auraphp/Aura.Session#61] opened 2017-09-10 05:58 UTC
Hi,
I am using this library for my application using localhost. segment is storing values when i access the site using http://localhost:8080 but it is not saving values if i access the same site using http://127.0.0.1:8080. 
Please help me to fix this issue.

**Comment by harikt** [comment] 2017-09-11 04:52
Show us some code what you are doing ?

How are you calling the server etc (Eg : Is it via nginx, apache or php default web server ) .

What OS are you dealing with etc.

**Comment by rakshithsj30** [comment] 2017-09-11 05:35
Hi,
I am using apache xampp. In one of my php(login.php) i will set the session variable:
$segment->set('logged_in', 'true'); after successful login.

In another php (dashboard.php), i will check whether user is logged in or not using:
$logged_in=$segment->get('logged_in', 'false'); 

if i visit the site using this url  http://localhost:8080, then $logged_in returns true. 

if i visit the site using ip, that is http://127.0.0.1:8080 then $logged_in returns false. In this case session is not holding any values. 

I am struggling to fix the error because every thing works fine if i use http://localhost:8080 but if i access the site using 127.0.0.1:8080, session is not working

**Comment by harikt** [comment] 2017-09-26 16:37
@rakshithsj30 I think you should not worry too much on accessing IP. You should test how it works on when you use a domain / virtual host.

**Comment by SaphiLC** [comment] 2017-10-04 23:53
its probably creating 2 cookies, one for each domain, i thinks that normal behavior

**Comment by harikt** [comment] 2023-09-23 09:57
I am closing this as this is not a bug with the library.

**Closed as completed by harikt** 2023-09-23 09:57 UTC
