### ISSUE TITLE
PHP7 session_regenerate_id(): Failed to create(read) session ID: user (path: )

### ISSUE THREAD

**Issue by jakejohns** [auraphp/Aura.Session#48] opened 2016-03-18 00:34 UTC
I see Travis is angry with #46, #47 on PHP7... but I dont think I did anything to break it.

> 1) Aura\Session\SessionTest::testGetAndRegenerateId
> session_regenerate_id(): Failed to create(read) session ID: user (path: )

Possibly related?
https://bugs.php.net/bug.php?id=70871

Any ideas?

**Comment by harikt** [comment] 2016-03-18 11:46
From my experiments from https://3v4l.org/AbalN and https://3v4l.org/ZdENi it looks to me not a bug in php. But on the session save handler. But I am not sure whether my understanding / assumptions are correct or wrong.

**Comment by harikt** [comment] 2016-03-18 11:59
oh oh I understand the reason now.

> The read callback must always return a session encoded (serialized) string, or an empty string if there is no data to read.

https://3v4l.org/bdQNv 

May be you could fix the `FakeSessionSaveHandler` ?

**Comment by harikt** [comment] 2016-03-18 12:03
I have created a branch. Lets see https://github.com/auraphp/Aura.Session/pull/49 .

**Comment by harikt** [comment] 2016-03-18 12:20
I have closed #49 due to various fixes I can send on a single PR  https://github.com/auraphp/Aura.Session/pull/50 . Hopefully I guess if that particular commit is merged your PR's will be green. I will wait for @pmjones to look into the PR and merge if he is happy.

**Comment by harikt** [comment] 2016-04-11 04:53
Closing for this is fixed in #50 which is merged for the current time.

**Closed as completed by harikt** 2016-04-11 04:53 UTC
